feature/KAS 4380 bulk beslissingen markeren
kanselarij-vlaanderen/digital-signing-service pull request #38
Opened 2023-11-07 14:17 UTC by SchrodingersCat00

- add mark-pieces-for-signing route
- add mark-pieces-for-singing implementation
- add resource base constants
- move document base uri to config
- move resource base uri to config

2023-11-09 16:24 UTC, sergiofenoll requested changes

2023-11-09 20:31 UTC, ValenberghsSven commented
Can't get this to work locally, might be a me issue.
But there does not seem to be a dispatcher change for this new route.
So you shouldn't be able to reach this from frontend.

2023-11-10 08:28 UTC, sergiofenoll commented
> Can't get this to work locally, might be a me issue (getting 404 when calling the service) But there does not seem to be a dispatcher change for this new route. So you shouldn't be able to reach this from frontend.

Made a mistake while merging master into this branch yesterday. Should work now.

2023-11-13 09:48 UTC, ValenberghsSven commented
Testing
Will update this as I go and manually fix where possible:
- `dossier:openingsdatum` should be date, we are inserting a datetime (fixed locally)
- since we query once and then start creating data in a for loop, it is possible to create double (or more) sing-flow/marking for each piece. Thinking we need a `filter not exists` in the insert query so we stop doing anything if a marking activity already exists at that time.

2023-11-13 16:00 UTC, ValenberghsSven approved these changes

2023-11-13 17:29 UTC, merged