KAS-4948: Retry flow polling with all sessions
kanselarij-vlaanderen/digital-signing-service pull request #54
Opened 2024-12-12 09:45 UTC by sergiofenoll

https://kanselarij.atlassian.net/browse/KAS-4948

Users can have multiple sessions and we currently don't have a way to determine which session is related to which signing flow (this is based on which OVO code was used to start the signing flow). So for now we will retry the polling with all the sessions we have, and if none work we will create new sessions for each OVO code and try with each.

2024-12-12 09:45 UTC, sergiofenoll commented on authentication.py
> -def signinghub_session_required(f):
Unused code.

2024-12-12 16:31 UTC, ValenberghsSven requested changes
testing locally, when we fail to create a machine session we don't catch/show the error. (Locally I have the old credentials)
The error gets thrown way later (like when you change something and it livereloads)
Is that something we can fix? could be sidetracking so can ignore.
[digital-signing-local.txt](https://github.com/user-attachments/files/18114339/digital-signing-local.txt)

After that I locally removed the `limit 1` of the mentioned query, fixed the `signing_flow_uri` not being passed in function, added mock data so that admin is in 2 orgs, and created 2 "valid" signinhub sessions with insert queries (sessions don't have any idea of ovo but wanted to test the for each loop)
The logs seem ok for the looping of session and try with ovo codes. No actual action occurs since I have no valid session, but both sessions are checked and not found valid, tried both ovo codes to create a new session
![image](https://github.com/user-attachments/assets/d7491d42-2ab8-4d8e-b89a-548dd34f77a5)

But again, there are no exception during that process, that gets thrown later when the next livereload happens. Is this "holding" resources back? Just wondering if this is normal python behavior. 

The removal of the limit 1 may have side effects on the other places this method is used so not committing.

2024-12-13 08:27 UTC, sergiofenoll commented on lib/update_signing_flow.py
> +def _update_signing_flow(signing_flow):
missed that, sorry

2024-12-13 08:28 UTC, sergiofenoll commented on lib/update_signing_flow.py
> +        construct_get_signinghub_machine_user_session_query(creator["email"])
locally I removed the `limit 1`, but somehow I didn't manage to commit that

2024-12-13 10:19 UTC, ValenberghsSven approved these changes
Not retested, but changes after first review are what was requested so should be ok.

2024-12-13 10:20 UTC, merged